GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmlyIiwiaWF0IjoxNjc4OTYzNTg3LCJleHAiOjE2Nzg5NjM2MDJ9.bjwDjgRqKDXboTPs9XSMLp-_sptKe1p4tBibOi_A1X8

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Nir"
}

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmlyIiwiaWF0IjoxNjc4OTYzNTU5fQ.YrhJallrVLZiGw7dBJfsnKmoOSrAv1apgIemg2uyDvQ"
}


###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmlyIiwiaWF0IjoxNjc4OTYzNTU5fQ.YrhJallrVLZiGw7dBJfsnKmoOSrAv1apgIemg2uyDvQ"
}



